spring:
  application:
    name: Card-Managegr
  jackson:
    default-property-inclusion: NON_NULL
  sleuth:
    sampler:
      probability: 1.0

error-config:
  errorMapping: [
    { internalCode: "CAR001", internalMessage: [ { "lang": "en", "message": "Error to process the request." }, { "lang": "pt", "message": "Erro ao processar a requisição." } ], externalCode: "", externalMessage: "" },
  ]
